# Generated by Django 2.1.2 on 2019-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190215_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scan',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
