# Generated by Django 2.1.2 on 2019-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190215_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
