# Generated by Django 2.1.2 on 2019-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190215_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='scan',
            field=models.CharField(max_length=50),
        ),
    ]
